### PR TITLE
git-branch-status subtree

### PR DESCRIPTION
**Pull request by javabrett**
Create a subtree and symlink for bill-auger/git-branch-status.

### CODE REVIEW

**Comment by bill-auger** [comment]
@javabrett -

thanks for doing this i have not yet had the time to learn this new trick but let me explain my intention of the preparations i made recently

firstly the subtree-merge-prepare script  should be only in the subtree-merge-prepare branch - it is not relavent to the script functionality - it job is to add checkout the main script at the master tip into a staging branch (the monolithic branch) and to append the body of the GPL to the main script so that the staging branch will contain only the single main script which can be easily merged into @jwiegley collection without having to filter the README and LICENSE each time

so this PR should be closed because is it based off of the subtree-merge-prepare utility branch - the intention is to do the subtree merge against the monolithic branch - thanks

**Comment by javabrett** [comment]
> so that the staging branch will contain only the single main script which can be easily merged without the README and LICENSE clobbering anything at the destination - also no symlink nor subdirectory should be necessary - as i understand it should be possible in this way to merge my monolithic branch directly into the root of the git-scripts tree without conflict

Sure, I'm not a `git subtree` expert, or maybe that was not even the intended mechanism, but I figured it would at least need to add a dir (the subtree).  Happy to learn how to do this directly into the root.

> so this PR should be closed because is it based off of the subtree-merge-prepare utility branch which dos not even include the main git-branch-status script

Looks like I picked-up master @ d896562 which has the standard script with detached license, rather than the subtree-merge-prepare branch.  I don't know what `monolithic` should/would do.

By having a sub-directory and symlink, the separate license file problem is not a problem, the script refers to it and it sits there in the subtree, and the symlink points to it.

I didn't squash the history, which is perhaps a more-conventional approach.

**Comment by bill-auger** [comment]
ok yes i see that now - i was just confused by the reference from the comment on the subtree-merge-prepare branch

this subdirectory and symlink approach is certainly simpler for me to maintain - the monolithic branch contains only one single script that i figured would be more consistent with the existing collection which has no subdirectories - i suppose jwiegley can decide which is preferred

**Comment by jwiegley** [comment]
Having it live in its own directory makes subtree updating much easier.

**Comment by jwiegley** [comment]
@javabrett Is this in the state that you wanted merged now?

**Comment by bill-auger** [comment]
ok if this looks good to you guys 

my last commit in this PR is te current tip of my master:

refactor d89656288c2f05c3950c0f6121f4566552d2fc1b

**Comment by javabrett** [comment]
@jwiegley yep I think it's all good :ship:.

**Pull request merged**
